In [14]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv("/content/passwords 2.csv")
df.head()

                                                   passwords
password           length uppercase digits special     label
dJFCrn]            7      3         0      1            Weak
.2edlB             6      1         1      1            Weak
#:d*z|@`(1C        11     1         1      7          Medium
.Jau`2RJtBRnlWmTS: 18     8         1      3          Strong

In [16]:
# Automatically detect target column (last column)
target_column = df.columns[-1]

# Features (everything except target)
X = df.drop(target_column, axis=1)

# Label (target)
y = df[target_column]

print("Features:\n", X.head())
print("Labels:\n", y.head())

Features:
 Empty DataFrame
Columns: []
Index: [(password, length, uppercase, digits, special), (dJFCrn], 7, 3, 0, 1), (.2edlB, 6, 1, 1, 1), (#:d*z|@`(1C, 11, 1, 1, 7), (.Jau`2RJtBRnlWmTS:, 18, 8, 1, 3)]
Labels:
 password            length  uppercase  digits  special     label
dJFCrn]             7       3          0       1            Weak
.2edlB              6       1          1       1            Weak
#:d*z|@`(1C         11      1          1       7          Medium
.Jau`2RJtBRnlWmTS:  18      8          1       3          Strong
Name: passwords, dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [18]:
X.head()

Empty DataFrame
Columns: []
Index: [(password, length, uppercase, digits, special), (dJFCrn], 7, 3, 0, 1), (.2edlB, 6, 1, 1, 1), (#:d*z|@`(1C, 11, 1, 1, 7), (.Jau`2RJtBRnlWmTS:, 18, 8, 1, 3)]